"""add wiki_reference to pieces

Revision ID: 032a4c05d486
Revises: cf4393afb6e9
Create Date: 2026-08-19 12:26:53.646319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032a4c05d486'
down_revision: Union[str, Sequence[str], None] = 'cf4393afb6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('wiki_reference', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pieces', 'wiki_reference')
    # ### end Alembic commands ###
