"""add ondelete cascade to practice_sessions piece_id fk

Revision ID: 1ce470a538b2
Revises: c0f9b7288823
Create Date: 2026-08-13 10:08:02.611776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce470a538b2'
down_revision: Union[str, Sequence[str], None] = 'c0f9b7288823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: name both the dropped and
    # recreated constraint explicitly so downgrade can reference it back ###
    op.drop_constraint(op.f('practice_sessions_piece_id_fkey'), 'practice_sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('practice_sessions_piece_id_fkey'),
        'practice_sessions', 'pieces', ['piece_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: see upgrade() note ###
    op.drop_constraint(op.f('practice_sessions_piece_id_fkey'), 'practice_sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('practice_sessions_piece_id_fkey'),
        'practice_sessions', 'pieces', ['piece_id'], ['id'],
    )
    # ### end Alembic commands ###
