"""add key, tempo, difficulty, instrument to pieces

Revision ID: 4fa03e8f6853
Revises: e842f0c2eda4
Create Date: 2026-08-12 17:37:40.665027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fa03e8f6853'
down_revision: Union[str, Sequence[str], None] = 'e842f0c2eda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


piece_difficulty = postgresql.ENUM(
    'beginner', 'intermediate', 'advanced', 'expert',
    name='piece_difficulty',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: native enum type must be
    # created explicitly (autogenerate omits the CREATE TYPE statement) ###
    piece_difficulty.create(op.get_bind())
    op.add_column('pieces', sa.Column('key', sa.String(length=50), nullable=True))
    op.add_column('pieces', sa.Column('tempo_bpm', sa.Integer(), nullable=True))
    op.add_column('pieces', sa.Column('difficulty', piece_difficulty, nullable=True))
    op.add_column('pieces', sa.Column('instrument', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: drop the enum type after the
    # column that depends on it, otherwise DROP TYPE fails ###
    op.drop_column('pieces', 'instrument')
    op.drop_column('pieces', 'difficulty')
    op.drop_column('pieces', 'tempo_bpm')
    op.drop_column('pieces', 'key')
    piece_difficulty.drop(op.get_bind())
    # ### end Alembic commands ###
