"""create sheet resources table

Revision ID: 98de3e5e1c66
Revises: 9d9395c074df
Create Date: 2026-08-12 14:48:33.980566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98de3e5e1c66'
down_revision: Union[str, Sequence[str], None] = '9d9395c074df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('url', 'physical', 'local-doc', name='sheet_resource_kind'), nullable=False),
    sa.Column('reference', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_resources_piece_id'), 'sheet_resources', ['piece_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: drop the enum type after the
    # table that depends on it, otherwise DROP TYPE fails ###
    op.drop_index(op.f('ix_sheet_resources_piece_id'), table_name='sheet_resources')
    op.drop_table('sheet_resources')
    sa.Enum(name='sheet_resource_kind').drop(op.get_bind())
    # ### end Alembic commands ###
