"""add status and tags to pieces

Revision ID: a15411f16eb2
Revises: 87fcfed122de
Create Date: 2026-08-11 12:02:23.338881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a15411f16eb2'
down_revision: Union[str, Sequence[str], None] = '87fcfed122de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


piece_status = postgresql.ENUM(
    'backlog', 'learning', 'memorized', 'maintaining', 'performance-ready', 'archived',
    name='piece_status',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: native enum type must be
    # created explicitly (autogenerate omits the CREATE TYPE statement) ###
    piece_status.create(op.get_bind())
    op.add_column('pieces', sa.Column('status', piece_status, server_default='backlog', nullable=False))
    op.add_column('pieces', sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: drop the enum type after the
    # column that depends on it, otherwise DROP TYPE fails ###
    op.drop_column('pieces', 'tags')
    op.drop_column('pieces', 'status')
    piece_status.drop(op.get_bind())
    # ### end Alembic commands ###
