"""add uploaded kind and file metadata to sheet_resources

Revision ID: a64b40e5a8aa
Revises: e0d2faf31d9a
Create Date: 2026-08-17 07:59:22.933784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b40e5a8aa'
down_revision: Union[str, Sequence[str], None] = 'e0d2faf31d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: autogenerate doesn't detect
    # new enum values on an existing Postgres type, so the ADD VALUE below was added manually ###
    op.execute("ALTER TYPE sheet_resource_kind ADD VALUE 'uploaded'")
    op.add_column('sheet_resources', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('sheet_resources', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('sheet_resources', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('sheet_resources', sa.Column('storage_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: Postgres has no ALTER TYPE
    # ... DROP VALUE, so removing 'uploaded' means recreating the enum type without it. This
    # fails (by design) if any row still has kind='uploaded' - such rows must be migrated or
    # deleted before downgrading past this revision. ###
    op.drop_column('sheet_resources', 'storage_key')
    op.drop_column('sheet_resources', 'file_size_bytes')
    op.drop_column('sheet_resources', 'content_type')
    op.drop_column('sheet_resources', 'original_filename')
    op.execute("ALTER TYPE sheet_resource_kind RENAME TO sheet_resource_kind_old")
    op.execute("CREATE TYPE sheet_resource_kind AS ENUM ('url', 'physical', 'local-doc')")
    op.execute(
        "ALTER TABLE sheet_resources ALTER COLUMN kind TYPE sheet_resource_kind "
        "USING kind::text::sheet_resource_kind"
    )
    op.execute("DROP TYPE sheet_resource_kind_old")
    # ### end Alembic commands ###
