"""create repertoire lists and pieces association table

Revision ID: c0f9b7288823
Revises: 4fa03e8f6853
Create Date: 2026-08-12 22:26:23.837959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f9b7288823'
down_revision: Union[str, Sequence[str], None] = '4fa03e8f6853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repertoire_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repertoire_list_pieces',
    sa.Column('repertoire_list_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_list_id'], ['repertoire_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repertoire_list_id', 'piece_id')
    )
    op.create_index(op.f('ix_repertoire_list_pieces_piece_id'), 'repertoire_list_pieces', ['piece_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repertoire_list_pieces_piece_id'), table_name='repertoire_list_pieces')
    op.drop_table('repertoire_list_pieces')
    op.drop_table('repertoire_lists')
    # ### end Alembic commands ###
