"""add thumbnail_key to sheet_resources

Revision ID: cf4393afb6e9
Revises: a64b40e5a8aa
Create Date: 2026-08-19 09:18:36.074127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4393afb6e9'
down_revision: Union[str, Sequence[str], None] = 'a64b40e5a8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_resources', sa.Column('thumbnail_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_resources', 'thumbnail_key')
    # ### end Alembic commands ###
