"""add goal_text and goal_target_date to pieces

Revision ID: dd2041351b60
Revises: 1ce470a538b2
Create Date: 2026-08-13 10:53:49.418871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2041351b60'
down_revision: Union[str, Sequence[str], None] = '1ce470a538b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('goal_text', sa.Text(), nullable=True))
    op.add_column('pieces', sa.Column('goal_target_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pieces', 'goal_target_date')
    op.drop_column('pieces', 'goal_text')
    # ### end Alembic commands ###
