"""add is_favorite to pieces

Revision ID: e842f0c2eda4
Revises: 98de3e5e1c66
Create Date: 2026-08-12 16:38:00.150712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e842f0c2eda4'
down_revision: Union[str, Sequence[str], None] = '98de3e5e1c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pieces', 'is_favorite')
    # ### end Alembic commands ###
